src/Entity/Avis.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AvisRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Avis
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $author;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $create_at;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Galerie", inversedBy="avis",cascade={"persist"})
     * @ORM\JoinColumn(name="avis_image_id", referencedColumnName="id")
     */
    private $avis_image;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Response", mappedBy="idAvis")
     */
    private $responses;
    

    public function __construct()
    {
        $this->responses = new ArrayCollection();
    }

    /**
     * @ORM\PrePersist
     */
    public function prePersist()
    {
        if (!$this->getCreateAt()) {
            $this->setCreateAt(new \DateTime());
        }

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->create_at;
    }

    public function setCreateAt(\DateTimeInterface $create_at): self
    {
        $this->create_at = $create_at;

        return $this;
    }


    /**
     * Set the value of id
     *
     * @return  self
     */ 
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of avis_image
     */ 
    public function getAvis_image()
    {
        return $this->avis_image;
    }

    /**
     * Set the value of avis_image
     *
     * @return  self
     */ 
    public function setAvis_image($avis_image)
    {
        $this->avis_image = $avis_image;

        return $this;
    }

    /**
     * @return Collection|Response[]
     */
    public function getResponses(): Collection
    {
        return $this->responses;
    }

    public function addResponse(Response $response): self
    {
        if (!$this->responses->contains($response)) {
            $this->responses[] = $response;
            $response->setIdAvis($this);
        }

        return $this;
    }

    public function removeResponse(Response $response): self
    {
        if ($this->responses->contains($response)) {
            $this->responses->removeElement($response);
            // set the owning side to null (unless already changed)
            if ($response->getIdAvis() === $this) {
                $response->setIdAvis(null);
            }
        }

        return $this;
    }
}

src/Controller/BlogController.php
<?php

namespace App\Controller;

use App\Entity\BlogPost;
use App\Form\CommentType;
use App\Entity\BlogComment;
use App\Form\EntryFormType;
use App\Repository\TagRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class BlogController extends Controller

{

    private $entityManager;

    private $authorRepository;
    private $blogPostRepository;
     private $onLine;


    public function __construct(EntityManagerInterface $entityManager, HomeController $online)
    {
    $this->entityManager = $entityManager;
    $this->online = $online;
    $this->blogPostRepository = $entityManager->getRepository('App:BlogPost');
    $this->userRepository = $entityManager->getRepository('App:User');
    $this->tagRepository = $entityManager->getRepository('App:Tag');
    }


    /**
     * @Route("/blog", name="blog")
     */
    public function index(PaginatorInterface $paginator, Request $request)
    {
        $query = $this->blogPostRepository->getTagsMeta();
        $AllBlogPost = $this->blogPostRepository->getAllTagsMeta();
        //dump($query);

        //$query = $this->blogPostRepository->findBy(array(),array('id' => 'DESC'));

        $paginator  = $this->get('knp_paginator');
        $online = $this->online->userRepository->findAll();;
        //dump($online);
        $pagination = $paginator->paginate(
            $query, /* query NOT result */
            $request->query->getInt('page', 1)/*page number*/,
            $request->query->getInt('limit', 3)
        );
        //dump($paginator);
        return $this->render('blog/blog.html.twig', [
            'blogPosts' => $pagination, 'pagination' => $pagination, 'online' => $online
        ]);
    }

    /**
     * @Route("/blog/view/{id}", name="blog_view")
     */
    public function blogDetails(Request $request, EntityManagerInterface $em, $id)
    {



        $article = $this->getDoctrine()
        ->getRepository(BlogPost::class)
        ->find($id);

      if (!$article) {
        throw $this->createNotFoundException(
            'No product found for id '.$id
        );
    }

    $comments = $this->getDoctrine()
    ->getRepository(BlogComment::class)
    ->findBy(array('comment_post' => $id));

    $comment = new BlogComment();
    $author = $this->userRepository->findOneByUsername($this->getUser()->getUserName());
    $comment->setAuthor($author);
    $comment->setCommentPost($article);
    $form = $this->createForm(CommentType::class, $comment);
    
    $form->handleRequest($request);

    if($form->isSubmitted() && $form->isValid()){

        $em = $this->getDoctrine()->getManager();
        $em->persist($comment);
        $em->flush();

        return $this->redirectToRoute('blog_view', ['id' => $id]);
    }
        return $this->render('blog/details.html.twig', [
            'blogPosts' => $article, 'form' => $form->createView(), 'comments' => $comments
        ]);
    }


/**
 * @Route("/create-entry", name="admin_create_entry")
 *
 * @param Request $request
 *
 * @return \Symfony\Component\HttpFoundation\Response
 */
public function createEntryAction(Request $request)
{
    $blogPost = new BlogPost();
    

    $author = $this->userRepository->findOneByUsername($this->getUser()->getUserName());
    $blogPost->setAuthor($author);

    $form = $this->createForm(EntryFormType::class, $blogPost);
    $form->handleRequest($request);

    // Check is valid
    if ($form->isSubmitted() && $form->isValid()) {
        $this->entityManager->persist($blogPost);
        $this->entityManager->flush($blogPost);

        $this->addFlash('success', 'Votre post à bien été créé');

        return $this->redirectToRoute('admin_entries');
    }

    return $this->render('default/admin/entry_form.html.twig', [
        'form' => $form->createView()
        ]);
    }

    /**
    * @Route("/modify-entry/{id}", name="admin_modify_entry")
    *
    * @param Request $request
    *
    * @return \Symfony\Component\HttpFoundation\Response
    */
   public function modifyEntryAction(Request $request, $id)
   {
        $em = $this->getDoctrine()->getManager();
        $modify_post = $em->getRepository('App:BlogPost')->find($id);
        
       $form = $this->createForm(EntryFormType::class, $modify_post);
       $form->handleRequest($request);
   
       // Check is valid
       if ($form->isSubmitted() && $form->isValid()) {
           $this->entityManager->persist($modify_post);
           $this->entityManager->flush($modify_post);
   
           $this->addFlash('success', 'Votre post à bien été modifié');
   
           return $this->redirectToRoute('admin_entries');
       }
   
       return $this->render('default/admin/entry_form.html.twig', [
           'form' => $form->createView()
           ]);
       }

}

templates/blog/blog.html.twig
{% extends "default/base.html.twig" %}

{% block title %}Blog{% endblock %}

{% block header %}
    {{ include('default/header.html.twig') }}
{% endblock %}

{% block menu %}
    {{ include('default/menu.html.twig') }}
{% endblock %}

{% block body %}
<div class="container">
    {# bloc utilisateurs en ligne visible si user admin #}
    <div class="cardUser">
    {% include "default/dataUserOnline.html.twig" %}
    </div>
 {# fin de bloc utilisateurs en ligne #}
    {% for blogPost in blogPosts %}
         <div class="row">
                <div class="col s12 m7 l12">
                    <div class="tags">
                        {% for tags in blogPost.blogTags %}
                        <div class="chip">
                            {{ tags.name }}
                          </div>
                        {%  endfor %}
                      </div>
                  <div class="card hoverable">
                    <div class="card-image">

                      <img src="https://picsum.photos/900/300/?image={{ random(1000) }}" alt="L'image n'a pas pu se charger">
                      {% if app.user.username == blogPost.author %}
                      <a class="btn-floating halfway-fab waves-effect waves-light orange pulse" href="{{ path('admin_modify_entry', {'id': blogPost.id}) }}"><i class="material-icons">mode_edit</i></a>
                      {% endif %}
                      
                      <span class="card-title bold">{{ blogPost.title }}</span>
                     
                    </div>
                    <div class="card-content">
                            <p>Poste le
                                    {{ blogPost.createdAt|date("m/d/Y H:i:s", "Europe/Paris") }}
                                </p>
                                <hr>
                      <p>{{ blogPost.description }}</p>
                      <blockquote><div class="badge">{{ blogPost.blogComments|length }} commentaires</div></blockquote> 
                    </div>
                    <div class="card-action">
                      <a href="{{ path('blog_view', {'id': blogPost.id}) }}">Lire plus...</a>
                      
                    </div>
                  </div>
                </div>
              </div>
    {% endfor %}
  <div class="row">
  {{ knp_pagination_render(pagination) }}
  </div>
</div>
{% endblock %}

templates/blog/details.html.twig
{% extends "default/base.html.twig" %}

{% block title %}Details{% endblock %}

{% block header %}
    {{ include('default/header.html.twig') }}
{% endblock %}

{% block menu %}
    {{ include('default/menu.html.twig') }}
{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col s12 m7 l12">
                <div class="card hoverable">
                    <div class="card-image">
                        <img src="https://picsum.photos/900/300/?image={{ random(1000) }}" alt="L'image n'a pas pu se charger">
                        {% if app.user.username == blogPosts.author %}
                            <a class="btn-floating halfway-fab waves-effect waves-light orange pulse" href="{{ path('admin_modify_entry', {'id': blogPosts.id}) }}">
                                <i class="material-icons">mode_edit</i>
                            </a>
                        {% endif %}
                        <span class="card-title bold">{{ blogPosts.title }}</span>
                    </div>
                    <div class="card-content">
                        <p>Poste le
                            {{ blogPosts.createdAt|date("m/d/Y H:i:s", "Europe/Paris") }}
                        </p>
                        <hr>
                        <p>{{ blogPosts.body }}</p>
                    </div>
                    <div class="card-action">
                        <a href="{{ path('blog') }}">Retour...</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% if comments !='' %}
      {% for bcomments in comments %}
      <div class="container">
          <div class="row">
      <div class="col s12 m7 l12">
          <div class="card-panel grey lighten-5 z-depth-1">
            <div class="row valign-wrapper">
              <div class="col s2">
                <img src="{{ asset('build/images/avatars.png') }}" alt="" class="circle responsive-img"> <!-- notice the "circle" class -->
              </div>
              <div class="col s10">
                <span class="black-text">
                    <p>Poste le
                        {{ bcomments.createAt|date("m/d/Y H:i:s", "Europe/Paris") }} par <span style="font-weight: bold">{{ bcomments.email }}</span>
                    </p>
                    <hr>
                    <p>{{ bcomments.content }}</p>
                </span>
              </div>
            </div>
          </div>
        </div>
        </div>
      </div>
      
      {% endfor %}
    {% endif %}
    <div class="container">
        <div class="row">
            <div class="col s12 m7 l12">
                <div class="card hoverable">
                    <div class="card-content">
                        <h4>Poster un commentaire :</h4>
                        {{ form_start(form)}}
                        <div class="row">
                          <div class="input-field col s12">
                              {{form_label (form.email)}}
                              {{form_widget (form.email)}}
                          </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                        {{form_label (form.content)}}
                        {{form_widget (form.content, {'attr': {'class':'materialize-textarea'}})}}
                      </div>
                    </div>
                    </div>
                    <div class="card-action">
                        <button class="btn waves-effect waves-light" type="submit" name="action">Commenter
                        </button>
                    </div>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/blog/view.html.twig
{% extends "default/base.html.twig" %}

{% block title %}View{% endblock %}

{% block header %}
    {{ include('default/header.html.twig') }}
{% endblock %}

{% block menu %}
    {{ include('default/menu.html.twig') }}
{% endblock %}

{% block body %}
<div class="container">
    {% for blogPost in blogPosts %}
         <div class="row">
                <div class="col s12 m7 l12">
                  <div class="card hoverable">
                    <div class="card-image">
                      <img src="https://picsum.photos/900/300/?image={{ random(1000) }}" alt="L'image n'a pas pu se charger">
                      {% if app.user.username == blogPost.author %}
                      <a class="btn-floating halfway-fab waves-effect waves-light orange"><i class="material-icons">mode_edit</i></a>
                      {% endif %}
                      <span class="card-title bold">{{ blogPost.title }}</span>
                    </div>
                    <div class="card-content">
                            <p>Poste le
                                    {{ blogPost.createdAt|date("m/d/Y H:i:s", "Europe/Paris") }}
                                </p>
                                <hr>
                      <p>{{ blogPost.description }}</p>
                    </div>
                    <div class="card-action">
                      <a href="{{ path('blog_view', {'id': blogPost.id}) }}">Lire plus...</a>
                    </div>
                  </div>
                </div>
              </div>
    {% endfor %}
</div>
{% endblock %}
<div class="row">
    {{ knp_pagination_render(pagination) }}
</div>